### ISSUE TITLE
Attribution of BTC power law model

### ISSUE THREAD

**Issue by gsantostasi** [BitboBTC/Feedback#10]
Could you please change the attribution of the Power Law Model to G. Santostasi @gsantostasi. HCBurger quotes my reddit post as the source of his model but for some reason people ignore this and give credit to him for the model. I posted the Reddit post much earlier than HCBurger Medium article: https://www.reddit.com/r/Bitcoin/comments/9cqi0k/bitcoin_power_law_over_10_year_period_all_the_way/. 
Thanks,
Giovanni

**Comment by JTuwiner** [comment]
Hey Giovanni, yes we'd love to add it. Can you please let me know exactly which URL you want me to site as the source? The reddit thread?
