### ISSUE TITLE
Add "Range" for the selected chart view on Mobile

### ISSUE THREAD

**Issue by morrisonbrett** [BitboBTC/Feedback#11]
Desktop looks great, now please implement this on mobile: https://github.com/BitboBTC/Feedback/issues/2

**Comment by JTuwiner** [comment]
This is done. Enjoy! And as always, if you have any other requests please let me know.

**Comment by morrisonbrett** [comment]
@JTuwiner looks great! On behalf of all users - thanks for implementing this!
