### ISSUE TITLE
Halving prediction?

### ISSUE THREAD

**Issue by ropersino** [BitboBTC/Feedback#13]
Folks - love your work. Awesome tool I do use everyday. Could you add a simple 'Halving Date Forecast'or 'Count down' expressed as a date and time? Natural place would be under 'Blockchain Stats'.
My bad if it is already in the product?
Again: big kudos & thank you.
Rgds
S

**Comment by JTuwiner** [comment]
<img width="381" alt="Screenshot 2024-01-29 at 11 28 28 AM" src="https://github.com/BitboBTC/Feedback/assets/2924924/da206665-3439-4f9f-9655-42035c38c93b">


Hey @ropersino , thanks for the feedback! I added this section yesterday. Is this what you mean?

Also, within a week or so we'll be launching drag and drop so you can move panels around in the order you want based on the data you like. Then you'd be able to move this panel of "Next Halving" up higher on the dashboard.

**Comment by ropersino** [comment]
Awesome. My bad. I likely had not done a refresh.
Much better than what I proposed!

**Comment by JTuwiner** [comment]
No worries! Feel free to suggest any other ideas if you have and we'll do our best to add.
