### ISSUE TITLE
Can you provide definitions/clarification on terms used on the dashboard?  

### ISSUE THREAD

**Issue by ChandlerBrig** [BitboBTC/Feedback#14]
Can you provide definitions/clarification on terms used on the dashboard?  

for example, under the Closed Ended Funds section, what does "OBTC.U to Price" or "OBTC.U to Premium"  mean?  Why/How's that different from OBTC Premium? 

![image](https://github.com/BitboBTC/Feedback/assets/101834807/5e362f24-ae62-418a-9320-ecbaf8625a03)

**Comment by JTuwiner** [comment]
OBTC price is the price of a share of https://ospreyfunds.io/products/obtc/

Premium is the price of BTC according to the OBTC price compared to the actual BTC price
