### ISSUE TITLE
Keep this project going it's useful.

### ISSUE THREAD

**Issue by dilbertsintheoffice** [BitboBTC/Feedback#15]
I am using the charts for as inspired by planb, stock to flow, it keeps saying I'm not human and provides no other option to verify human life form, carbon based life-form.  I can get to the main web page ok, just not the charts. Thanks.

eg: https://charts.bitbo.io/sma1458/
error: Looks like you are not a human.

**Comment by JTuwiner** [comment]
Hi, if you are using a VPN you may be blocked by our spam detector.

**Comment by dilbertsintheoffice** [comment]
Yes I am. however I was using it when it was working. I guess I'll try various connections and see which one works.

**Comment by JTuwiner** [comment]
Ok, sorry about that.  We're working on fixing this as a lot of people have reported this problem
