### ISSUE TITLE
negative premium on GBTC is off by almost 0.5%

### ISSUE THREAD

**Issue by MajorGeneralHammond** [BitboBTC/Feedback#16]
According to my calculations, your negative premium on GBTC is off by almost 0.5%  Please see screenshot and math. Thank you.
<img width="1524" alt="Screen Shot 2024-02-05 at 1 18 01 PM" src="https://github.com/BitboBTC/Feedback/assets/151682320/08aa7480-b068-4133-9a36-6cc325e28666">

**Comment by JTuwiner** [comment]
you're right. not sure what happened, could be the BTC per share changed recently? anyway, i re-did the calc and we'll push it live soon. Thanks!

**Comment by MajorGeneralHammond** [comment]
Great! And so sorry I missed all those tags you put me in over the last few weeks. I need to get better at checking my notifications.  I have reliable numbers of bitcoin per share for GBTC, FBTC, and BITB and I think IBIT.  I'll tag you on twitter with them, just incase they're meaningful to you.

**Comment by JTuwiner** [comment]
No worries, thanks!
I think I also got those. I'm surprised the other ETFs have not published the numbers.

**Comment by JTuwiner** [comment]
@MajorGeneralHammond fixed now
