### ISSUE TITLE
Do not understand the numbers

### ISSUE THREAD

**Issue by ghost** [BitboBTC/Feedback#19]
First of all thank you for the great chart.
And thanks to @gsantostasi for his work.

But honestly I do not understand the numbers and the way they are calculated. I compare the numbers with:

https://bitcoinfairprice.com

There it is well explained how the numbers are calculated.

I do compare them with your chart, the data from yesterday (Feb 20, 2024).

BitcoinFairPrice.com:

Fair Price: $61,078
Bottom price: $25,653

Bitbo Chart:

Red (bottom price?): $25,717.23
Green (fair Price?): $72,480.99
Purple: (???): 286,068.09

Could you please enlighten what these numbers mean, especially the purple one. And check if the fair price is calculated correctly.

**Comment by JTuwiner** [comment]
<img width="894" alt="Screenshot 2024-02-21 at 8 55 07 AM" src="https://github.com/BitboBTC/Feedback/assets/2924924/b541b851-a833-438b-ac21-dff1aff0dec7">

https://medium.com/quantodian-publications/bitcoins-natural-long-term-power-law-corridor-of-growth-649d0e9b3c94

our code: 


<img width="650" alt="Screenshot 2024-02-21 at 8 55 22 AM" src="https://github.com/BitboBTC/Feedback/assets/2924924/cfdd76d1-dca5-4511-b0eb-8b9264650caa">
