### ISSUE TITLE
Add "Range" for the selected chart view

### ISSUE THREAD

**Issue by morrisonbrett** [BitboBTC/Feedback#2]
As the user clicks / taps each chart view (1H, 1D, 7D, 1M, YTD, 1Y, 5Y, ALL), show the high / low for each range.

Maybe put it under the green %, or just update the '24H HIGH', and '24H LOW' labels and data to reflect it. I think this would be very helpful. I find myself having to mouse / tap over the chart for the peaks and valleys to get these numbers. Adding this feature would make it so much easier, faster, and more accurate.

![image](https://user-images.githubusercontent.com/1159718/212944064-a7367f31-2dbb-41ba-8e8f-8ac8de57822e.png)

**Comment by JTuwiner** [comment]
That is a great idea. 

I think the best way to implement this would be to just replace "24H" with whatever range is selected on the chart. 

I'll talk to the dev team and see.

**Comment by morrisonbrett** [comment]
I think you're right. That would be the best way to implement it. No need to see the 24H HIGH / LOW at all times if the user goes out of their way to change the range. Thanks!

**Comment by JTuwiner** [comment]
We're working on this. Should be done Monday.

**Comment by JTuwiner** [comment]
This is live now. 

Please let me know about any other feature suggestions we can implement!

**Comment by morrisonbrett** [comment]
OMG - I just noticed this today that you finally did it. LOVE it. Well done and thank you!

**Comment by JTuwiner** [comment]
Thanks! Glad you like it.

Feel free to request any other features.

**Comment by morrisonbrett** [comment]
I noticed it's implemented on desktop only, not mobile. Would love to see it enabled on mobile too.
