### ISSUE TITLE
Add the date of ATH next to the ATH (USD) price

### ISSUE THREAD

**Issue by morrisonbrett** [BitboBTC/Feedback#20]
Maybe use a small font so you don't have to make too much space for it. Would be nice to see the datetimestamp for the ATH. Probably date is all that's needed (not time).

**Comment by JTuwiner** [comment]
I'm not sure if that fits well at the top, but maybe I can make a new section with the ATH and ATH date, and then other data like $ needeed to reach ATH, current % down from ATH etc

**Comment by morrisonbrett** [comment]
Yeah, that would be really helpful to see. I'm sure people would appreciate it!

**Comment by JTuwiner** [comment]
working on it!

have a few other things to do first, but I plan on adding this

**Comment by morrisonbrett** [comment]
Any update on when this may be started?

**Comment by JTuwiner** [comment]
We're planning to add a block called "ATH"

It will look like this: 


ATH Price

$73,794.02

Price Drawdown Since ATH

-4.62%

Days Since ATH

75

ATH Date

March 13, 2024

sound good?

**Comment by morrisonbrett** [comment]
Yes, that sounds really good!

In the spirit of Bitcoin, you could also add "ATH Block Height" at the time of ATH, right above or below "ATH Date".

**Comment by JTuwiner** [comment]
<img width="480" alt="Screenshot 2024-05-28 at 9 13 49 AM" src="https://github.com/BitboBTC/Feedback/assets/2924924/89438184-5942-4b0b-8c98-bab8bf833cae">


live now

**Comment by morrisonbrett** [comment]
Nice job, team! Just tweeted it.

https://x.com/morrisonbrett/status/1795474217674354771

**Comment by JTuwiner** [comment]
thanks for the tweet!

Your feedback is always appreciated...let me know any other ideas you have!
