### ISSUE TITLE
Bitcoin Halving Clock estimates wrong time to next halving (2024)

### ISSUE THREAD

**Issue by johnemb** [BitboBTC/Feedback#21]
The clock at https://bitbo.io/halving/ currently estimates 35 days 15 hours to the next halving, leading to date Apr 18, 2024.

At time of writing, we are at block 834523 which is 5477 blocks from 840000. Estimating 10 minutes per block, this is ( 5477 / 6 / 24 ) = 38.03 days. Mar 13 + 38 days = Apr 20.

This corresponds with alternative estimations such as the one at https://timechaincalendar.com/en, which also estimate Apr 20, 2024.

**Comment by JTuwiner** [comment]
We don't assume 10 minutes per block. 

Blocks have been coming in around 9.5 mins over last 4 periods

https://explorer.btc.com/btc/insights-difficulty
