### ISSUE TITLE
Bitcoin - days since last all time high

### ISSUE THREAD

**Issue by Shasha-101** [BitboBTC/Feedback#22]
I guess there is an issue with this chart 
https://charts.bitbo.io/days-since-high/, 
After 2021 the phase has not changed, show the same color. 
It has not updated/color changed to next phase. Please take a look at it.
![image](https://github.com/BitboBTC/Feedback/assets/57656504/ace08621-617c-40d5-927b-4901d17e14b2)

**Comment by JTuwiner** [comment]
sent to dev team

**Comment by JTuwiner** [comment]
fixed, correct @Shasha-101 ?
