### ISSUE TITLE
Add Canadian ETF Premiums Back

### ISSUE THREAD

**Issue by juil** [BitboBTC/Feedback#23]
Before the US bitcoin ETFs were approved, the dashboard used to have a module for the Canadian ETF premiums.

Would appreciate having that back.

**Comment by JTuwiner** [comment]
we haven't removed any panels. 
<img width="378" alt="Screenshot 2024-03-15 at 10 27 59 AM" src="https://github.com/BitboBTC/Feedback/assets/2924924/c55e7247-a422-4346-bac8-8ec3993a382d">
