### ISSUE TITLE
Inflation rate (monthly vs annual)

### ISSUE THREAD

**Issue by sabotag3x** [BitboBTC/Feedback#24]
Hello, I think the Bitcoin inflation rate shown on Bitbo is **annual**, not monthly as stated on the website.

6.25*144*365 = 328,500 BTC/year
reward * blocks per day * days per year = new BTC per year

328,500 - x
19,661,262 - 100

X = 1.67% **per year**

Source: Bitcoin **monthly** inflation (history and forecast) - https://charts.bitbo.io/inflation/

Let me know if I'm interpreting this data wrong.

Best regards.

**Comment by JTuwiner** [comment]
Checking with dev but you may be right.

Meaning it is the inflation by month in terms of the avg inflation by month, but yes it could be it's using the last year to compare. 

Does that make sense?
