### ISSUE TITLE
Clarify the Bitbo Indicators offers at https://whop.com/bitbo/

### ISSUE THREAD

**Issue by Michael-Lusk-2023** [BitboBTC/Feedback#26]
- specify which indicators are included in the "Basic Indicators" set offered at USD 39;
- specify which indicators are included in the "All indicators" set offered at USD 199.

Much appreciation for your charts!

**Comment by JTuwiner** [comment]
<img width="821" alt="Screenshot 2024-04-14 at 10 48 43 AM" src="https://github.com/BitboBTC/Feedback/assets/2924924/447bd8d3-ffa4-48ad-869d-717958674094">

https://indicators.bitbo.io/

**Comment by Michael-Lusk-2023** [comment]
Got it; thanks for the link!
