### ISSUE TITLE
Wrong ERA in text description explanation

### ISSUE THREAD

**Issue by xmlify** [BitboBTC/Feedback#31]
https://charts.bitbo.io/reward-era-comparison/

Has an out of date era.   The description reads,

"We are now in Era 4 since we have experienced three total halving events."

Suggest you remove this sentence from the description instead just changing 4 to 5, because it's relatively easy to find out which era we're in by poking at the realtime graph, and then the text won't be wrong in the future eras, too.

**Comment by JTuwiner** [comment]
thanks, we;ll fix it soon. we're about to move the site to a new backend with tons of new features, so once we do that it will be fixed.

**Comment by 102248898** [comment]
شكرا

**Comment by 102248898** [comment]
الحمدالله

**Comment by 102248898** [comment]
#32

**Comment by JTuwiner** [comment]
fixed, thanks! please let us know if you have any other feedback
