### ISSUE TITLE
Total Fees vs. Reward (24 hrs) is not as useful as the alternative

### ISSUE THREAD

**Issue by eragmus** [BitboBTC/Feedback#4]
Instead of showing fees vs. reward (reward = fees + subsidy), I think it is more useful to show fees vs. subsidy. What is of interest in bitcoin is when the market fees reach and exceed the exponentially-declining subsidy, not when fees reach and exceed reward.

![image](https://user-images.githubusercontent.com/11140618/236873711-100d42db-d806-4064-b633-b3be0bae6d3f.jpeg)

There also must be general confusion with what reward even refers to, since you can see below even the bitcoin mailing list has someone referring to the reward as if it is the subsidy. Even Greg doesn't dispute the terminology, as his post's happiness is based on fees getting high enough to approach the subsidy.

![image](https://user-images.githubusercontent.com/11140618/236873499-e743a2e6-0c7c-4ee4-a535-8c581c5140b2.jpeg)

Also here is the end result of a conversation with GPT-4, trying to see if I am missing something, like if fees vs. reward is better than fees vs. subsidy:

![image](https://user-images.githubusercontent.com/11140618/236877687-67d10f32-1729-4ef3-9415-bce0eaeede86.jpeg)

**Comment by JTuwiner** [comment]
So your proposal is to simply change "Total Fees vs. Rewards (24hrs)" to "Total Fees vs. Subsidy (24hrs)" in order to make it more clear?

**Comment by eragmus** [comment]
> So your proposal is to simply change "Total Fees vs. Rewards (24hrs)" to "Total Fees vs. Subsidy (24hrs)" in order to make it more clear? 

Hello, not just the wording, as the actual data should reflect the wording, but yes please.

**Comment by eragmus** [comment]
@JTuwiner Gentle reminder.

**Comment by eragmus** [comment]
> So your proposal is to simply change "Total Fees vs. Rewards (24hrs)" to "Total Fees vs. Subsidy (24hrs)" in order to make it more clear? 

Reminder

**Comment by eragmus** [comment]
@JTuwiner  Reminder

**Comment by JTuwiner** [comment]
<img width="378" alt="Screenshot 2023-12-15 at 9 27 13 AM" src="https://github.com/BitboBTC/Feedback/assets/2924924/0fd3b59c-cb16-45d3-84a9-376585abf76d">

this feature is done and ready to go. should be live within 48 hrs. 

@eragmus if you have any other stats you want on bitbo let me know and i'll try to add faster this time!
