### ISSUE TITLE
When changing window.title, keep the number of digits in the amount formatting consistent

### ISSUE THREAD

**Issue by ALeschinsky** [BitboBTC/Feedback#5]
As Bitcoin exchange rate fluctuates, the window title changes value - when formatting changes from "30,000" to "30,000.33" the string length changes and the title visually jumps. To prevent that undesireable and distracting effect, please only show the exchange rate down to the dollar, or always with the cents even when the cents are zeroes.

**Comment by JTuwiner** [comment]
Good idea. Sent to dev team to update this

**Comment by JTuwiner** [comment]
Fixed! Please let me know if you have any other ideas or feature suggestions

**Comment by ALeschinsky** [comment]
Thank you!
