### ISSUE TITLE
Realized MC / Realized price?

### ISSUE THREAD

**Issue by Ar1xjl** [BitboBTC/Feedback#6]
Do you see value on adding  few onchain ke metrics? Such as Realized Market Cap, realized price. Not too many but just a few useful ones?

**Comment by JTuwiner** [comment]
We have this chart: https://charts.bitbo.io/realized-price/

You're saying you'd want this number shown on the actual dashboard at bitbo.io home page? 

Which other ones interest you?

**Comment by Ar1xjl** [comment]
Hi Jordan, 
I was not even aware that section was available. Really cool. I only reached the https://bitbo.io <https://bitbo.io/> page and never found a link to this new section.

Yes I was thinking of adding that number to the Bitbo.io <http://bitbo.io/> home page, but this is much cooler. Probably worth a Twitter since I guess many like me would not know this was available and have to dig into other sources to get the number

Thanks a millón.

Juan Llauró
***@***.***
mobile: +54 911 6219-6852

**Comment by JTuwiner** [comment]
Hi Juan, thanks for your request here! It's in our pipeline of things to add. 

Any other feature requests?

**Comment by Ar1xjl** [comment]
Thanks sounds great.
The only other one I have thought about is Bitcoin realized Market cap vs
total global storage value.
There is a chart that Michael Saylor presented at one conference and was
produced by @coresus_BTC which I think is very valuable since it shows
Bitcoin share as a Store of value.

Juan

**Comment by JTuwiner** [comment]
if you can find me the chart we can add it to our to-do list!

**Comment by Ar1xjl** [comment]
This is the article where it was explained.

https://www.onceinaspecies.com/p/bitcoins-full-potential-valuation?utm_campaign=post&utm_medium=web

**Comment by Ar1xjl** [comment]
Would it be possible to incorporate the bitcoin distribution? As in this
attached chart?

Ideally with the possiblility to look into jow it looked like on a monhhly
basis.

The changes on distribution provide a hint on which price cohort is selling
and at which price consolidayions are forming..

Just a thought.

**Comment by JTuwiner** [comment]
Which chart is Bitcoin distribution?

**Comment by Ar1xjl** [comment]
This one that shows the ammount of coins that were transacted at each value



Juan Llauró
***@***.***
mobile: +54 911 6219-6852

**Comment by JTuwiner** [comment]
Oh yes, it's on our list. It might take some time though.

**Comment by Ar1xjl** [comment]
Cool thanks

Juan Llauró
***@***.***
mobile: +54 911 6219-6852

**Comment by JTuwiner** [comment]
BTW, you can see live Price / Realized Price multiple on home page

https://charts.bitbo.io/
<img width="376" alt="Screenshot 2023-12-04 at 6 54 15 PM" src="https://github.com/BitboBTC/Feedback/assets/2924924/9d8d480e-7c83-4490-b9b2-f4cf94ad1821">

**Comment by Ar1xjl** [comment]
Cool, thanks for the heads up!
Looks really nice.
