### ISSUE TITLE
Thanks for nice website

### ISSUE THREAD

**Issue by ybaidiuk** [BitboBTC/Feedback#7]
it would be great to have possibility mark my best chart and how folder with my charts. Probably counter (how meny peaple marked this chart to bookmarsk)

**Comment by JTuwiner** [comment]
What do you mean?

you're saying you would want to make a custom page that lists your favorite charts that you personally starred?

**Comment by ybaidiuk** [comment]
I do not have time now, to working on it, probably later)
It was just suggestion. 
Probably comment place not very good, and user need to login for saving this info(via google or lightning, or email))
![Screenshot 2023-08-10 at 01 46 35](https://github.com/BitboBTC/Feedback/assets/11969255/549b5c1c-7d1c-4bdb-b5e9-b5856e6a5da8)

**Comment by JTuwiner** [comment]
we're working on this. it should be added within 1 week

**Comment by JTuwiner** [comment]
this will be live within a couple weeks. thanks for tip.

**Comment by JTuwiner** [comment]
@ybaidiuk you can now favorite charts!

just make an account and then on chart page favorites are on right side

https://charts.bitbo.io/signup/

<img width="511" alt="Screenshot 2024-07-22 at 9 56 37 AM" src="https://github.com/user-attachments/assets/8160c3ad-ba12-4373-a1a5-28d1a449c32a">
