### ISSUE TITLE
The 24 hour volume feed seems to have broken and AUD price not correct

### ISSUE THREAD

**Issue by samzalin** [BitboBTC/Feedback#8]
Hi - great site, use this regularly.  Just seems like the 24 hour volume feed might have broken, been the same for days.  Secondly the AUD price of Bitcoin is also too low over the last few days.

**Comment by JTuwiner** [comment]
Should be fixed now. Thanks for the report.

the issues lately have mostly been due to issues with Binance API. 

Let me know if you have any other suggestions or feedback.

**Comment by samzalin** [comment]
Legend thankyou that looks like it’s working again now 😃 with 24 hour volume. The aud price still still seems a bit low but obviously could just be timing…CheersSam Sent from my iPhoneOn Aug 19, 2023, at 4:30 AM, Jordan Tuwiner ***@***.***> wrote:﻿
Should be fixed now. Thanks for the report.
the issues lately have mostly been due to issues with Binance API.
Let me know if you have any other suggestions or feedback.

**Comment by JTuwiner** [comment]
Can you explain more why you say it seems low? We can look into it.

**Comment by samzalin** [comment]
Jordan - seems good now, it was tracking about 5% below other sources on price but looks like it’s fine now. Thanks for getting onto everything so quickly, I probably use your price tool about 200 times a day 😂 .CheersSam Sent from my iPhoneOn Aug 19, 2023, at 5:28 AM, Jordan Tuwiner ***@***.***> wrote:﻿
Can you explain more why you say it seems low? We can look into it.

**Comment by JTuwiner** [comment]
I'm glad it's fixed now! If you have any other requests or feature ideas let me know. And always feel free to report bugs. Thnks!
